<?php
return [
	'two_title' =>'Two-step authentication setting',
	'two_description' =>'Every time you log in to GOOD ENOUGH FX, you will need your username and password, as well as the code generated by the Google Authenticator app on your smartphone.
	You need to enter the dynamic code to log in.
	This will effectively prevent your account from being compromised if your account password is leaked. ',
	'two_password' =>'Enter M4 password',
	'two_active' =>'Active application',
	'two_deactive' =>'Inactive application',
];